  0%|                                                                                                                                                                                                   | 0/100000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/main.py", line 119, in <module>
    next_obs, rewards, terminations, truncations, infos = envs.step(actions)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/vector/vector_env.py", line 204, in step
    return self.step_wait()
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 149, in step_wait
    ) = env.step(action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/wrappers/record_episode_statistics.py", line 94, in step
    ) = self.env.step(action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/wrappers/record_video.py", line 166, in step
    ) = self.env.step(action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/wrappers/time_limit.py", line 57, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/wrappers/env_checker.py", line 49, in step
    return env_step_passive_checker(self.env, action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py", line 208, in env_step_passive_checker
    result = env.step(action)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/gymnasium/envs/classic_control/cartpole.py", line 133, in step
    assert self.action_space.contains(
AssertionError: array([1], dtype=int32) (<class 'numpy.ndarray'>) invalid
